# Generated by Django 4.2.1 on 2023-06-14 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnpython', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='writer',
        ),
    ]
